version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: ["web"]  # Gọi Django từ entrypoint.sh

  celery_worker:
    build: .
    container_name: celery_worker
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: ["celery"]  # Gọi Celery từ entrypoint.sh

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
